### ISSUE TITLE
Special Stage Clear BGMs can silence Special Stage clear BGMs in other mods

### ISSUE THREAD

**Issue by TimerBunneh** [ShadowXeldron/ShadowXeldrons-S3AIR-Mods#1]
I noticed that somehow, my special stage clear BGM in my Sage mod was silent whenever this mod was above it. I took a peek and surprise, none of them ended with else...base.PlayMusic().

I've gone ahead and fixed this already, so feel free to see the related pull request.

**Comment by TimerBunneh** [comment]
[One fixed script for you, tested and working.](https://files.gamebanana.com/bitpit/main.lemon)

**Comment by ShadowXeldron** [comment]
Accepted upstream and split the Per-Character Themes rewrite into it's own folder.
